export const EVENT_FETCH_EVENT_DATA_SSR = 'EVENT_FETCH_EVENT_DATA_SSR';
export const EVENT_FETCH_EVENT_DATA = 'EVENT_FETCH_EVENT_DATA';
export const EVENT_FETCH_EVENT_DATA_FINISHED = 'EVENT_FETCH_EVENT_DATA_FINISHED';
export const EVENT_FETCH_EVENT_DATA_CANCEL = 'EVENT_FETCH_EVENT_DATA_CANCEL';

export const EVENT_FETCH_LOCATION_DATA = 'EVENT_FETCH_LOCATION_DATA';
export const EVENT_FETCH_LOCATION_DATA_FINISHED = 'EVENT_FETCH_LOCATION_DATA_FINISHED';
export const EVENT_FETCH_LOCATION_DATA_CANCEL = 'EVENT_FETCH_LOCATION_DATA_CANCEL';

export const EVENT_FETCH_IMAGE_URLS = 'EVENT_FETCH_IMAGE_URLS';
export const EVENT_FETCH_IMAGE_URLS_FINISHED = 'EVENT_FETCH_IMAGE_URLS_FINISHED';
export const EVENT_FETCH_IMAGE_URLS_CANCEL = 'EVENT_FETCH_IMAGE_URLS_CANCEL';

export const EVENT_FETCH_REVERSE_GEOCODE_SSR = 'EVENT_FETCH_REVERSE_GEOCODE_SSR';
export const EVENT_FETCH_REVERSE_GEOCODE = 'EVENT_FETCH_REVERSE_GEOCODE';
export const EVENT_FETCH_REVERSE_GEOCODE_FINISHED = 'EVENT_FETCH_REVERSE_GEOCODE_FINISHED';

export const EVENT_FETCH_DIRECTIONS = 'EVENT_FETCH_DIRECTIONS';
export const EVENT_FETCH_DIRECTIONS_FINISHED = 'EVENT_FETCH_DIRECTIONS_FINISHED';
