export const UPDATE_UPVOTES_LONG_POLL_STATUS = 'UPDATE_UPVOTES_LONG_POLL_STATUS';
export const FETCH_UPVOTES_START = 'FETCH_UPVOTES_START';
export const FETCH_UPVOTES_SUCCESS = 'FETCH_UPVOTES_SUCCESS';
export const FETCH_UPVOTES_ERROR = 'FETCH_UPVOTES_ERROR';
export const FETCH_UPVOTES_CANCEL = 'FETCH_UPVOTES_CANCEL';

export const UPDATE_UPVOTE_START = 'UPDATE_UPVOTE_START';
export const UPDATE_UPVOTE_SUCCESS = 'UPDATE_UPVOTE_SUCCESS';
export const UPDATE_UPVOTE_ERROR = 'UPDATE_UPVOTE_ERROR';
export const UPDATE_UPVOTE_CANCEL = 'UPDATE_UPVOTE_CANCEL';

