export const USER_UPDATE_USER_DATA = 'USER_UPDATE_USER_DATA';
export const USER_UPDATE_USER_DATA_SUCCESS = 'USER_UPDATE_USER_DATA_SUCCESS';
export const USER_UPDATE_USER_DATA_ERROR = 'USER_UPDATE_USER_DATA_ERROR';

export const USER_DELETE_USER = 'USER_DELETE_USER';
export const USER_DELETE_USER_SUCCESS = 'USER_DELETE_USER_SUCCESS';
export const USER_DELETE_USER_ERROR = 'USER_DELETE_USER_ERROR';

export const USER_UPDATE_USER_CREDENTIALS = 'USER_UPDATE_USER_CREDENTIALS';
export const USER_UPDATE_USER_CREDENTIALS_SUCCESS = 'USER_UPDATE_USER_CREDENTIALS_SUCCESS';
export const USER_UPDATE_USER_CREDENTIALS_ERROR = 'USER_UPDATE_USER_CREDENTIALS_ERROR';

export const USER_GET_INFO_SSR = 'USER_GET_INFO_SSR';
export const USER_GET_INFO = 'USER_GET_INFO';
export const USER_GET_INFO_SUCCESS = 'USER_GET_INFO_SUCCESS';
export const USER_GET_INFO_FAILED = 'USER_GET_INFO_FAILED';

export const USER_IMAGE_UPLOAD_ERROR = 'USER_IMAGE_UPLOAD_ERROR';

export const USER_GET_INCIDENTS = 'USER_GET_INCIDENTS';
export const USER_GET_INCIDENTS_SUCCESS = 'USER_GET_INCIDENTS_SUCCESS';
export const USER_GET_INCIDENTS_ERROR = 'USER_GET_INCIDENTS_ERROR';
