export const MAP_UPDATE_ZOOM = 'MAP_UPDATE_ZOOM';
export const MAP_UPDATE_CENTER = 'MAP_UPDATE_CENTER';
export const MAP_ONCLICK = 'MAP_ONCLICK';
export const MAP_UPDATE_POLYLINE = 'MAP_UPDATE_POLYLINE';
