export const HOME_LOCATION_SAVE_LOCATION = 'HOME_LOCATION_SAVE_LOCATION';
export const HOME_LOCATION_SAVE_LOCATION_SUCCESS = 'HOME_LOCATION_SAVE_LOCATION_SUCCESS';
export const HOME_LOCATION_SAVE_LOCATION_ERROR = 'HOME_LOCATION_SAVE_LOCATION_ERROR';
